language: java

env:
  - MOZ_HEADLESS=1
addons:
  firefox: "63.0"
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xzf geckodriver-v0.23.0-linux64.tar.gz
  - mv geckodriver lib/geckodriver
script:
  - travis_wait 30 xvfb-run ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)