language: java

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
script:
  - xvfb-run make test
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)